version: '3.8'

services:

  traefik:
    image: "traefik:v2.5"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: "frontend"
    environment:
      - BASE_URL=${BASE_URL}
    depends_on:
      - fastapi
    restart:
      always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`frontend.localhost`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"

  fastapi:
    build:
      context: ./backend
      dockerfile: Dockerfile.test
    container_name: "fastapi"
    environment:
      - ENVIRONMENT=test
      - TESTING=1
      - DATABASE_URL=postgres://postgres:postgres@postgresdb:5432/test
      - DATABASE_TEST_URL=postgres://postgres:postgres@postgresdb:5432/test
      - DATABASE_TEST_BACKEND_URL=postgres://postgres:postgres@postgresdb:5432/test-backend
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_FROM=${MAIL_FROM}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_SERVER=${MAIL_SERVER}
      - MAIL_FROM_NAME=${MAIL_FROM_NAME}
      - MAIL_TLS=${MAIL_TLS}
      - MAIL_SSL=${MAIL_SSL}
      - BASE_URL=http://api.localhost
    # command: bash -c "while true; do sleep 1; done"  # Infinite loop to keep container live doing nothing
    depends_on:
      - postgresdb
    restart: always
    command : uvicorn app.main:app --host 0.0.0.0 --port 8004
    expose:
      - 8004
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`api.localhost`) && PathPrefix(`/api`)"
      - "traefik.http.routers.fastapi.entrypoints=web"
      - "traefik.http.routers.fastapi.tls.certresolver=myresolver"

  postgresdb:
    build:
      context: ./backend/db
      dockerfile: Dockerfile.test
    container_name: "postgres"
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data/


volumes:
  db-data: