version: '3.8'

services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      - ENVIRONMENT=prod
      - TESTING=0
      - DATABASE_URL=postgres://postgres:postgres@web-db:5432/web_prod
    # command: bash -c "while true; do sleep 1; done"  # Infinite loop to keep container live doing nothing
    depends_on:
      - web-db
    restart: always

  web-db:
    build:
      context: ./backend/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data/

volumes:
  db-data: