version: '3.8'

services:

  fastapi:
    build:
      context: ./backend
      dockerfile: Dockerfile
    init: true
    container_name: fastapi
    ports:
      - 5678:5678
      - 8004:80
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - DATABASE_URL=postgres://postgres:postgres@database:5432/dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@database:5432/test 
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_FROM=${MAIL_FROM}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_SERVER=${MAIL_SERVER}
      - MAIL_FROM_NAME=${MAIL_FROM_NAME}
      - MAIL_TLS=${MAIL_TLS}
      - MAIL_SSL=${MAIL_SSL}
      - BASE_URL=${BASE_URL}
    volumes:
      - ./backend:/app
    command: 
      [
        "sh",
        "-c",
        "pip install debugpy && python -m debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn app.main:app --reload --host 0.0.0.0 --port 80",
      ]
    depends_on:
      - database

  database:
    build:
      context: ./backend/db
      dockerfile: Dockerfile.dev
    container_name: database
    init: true
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql/data/
 
volumes:
  db-data: