name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd nuxt-fastapi-docker-base
          docker-compose -f docker-compose-prod.yml --env-file .env.prod down
          git pull
          docker-compose -f docker-compose-prod.yml --env-file .env.prod build
          docker-compose -f docker-compose-prod.yml --env-file .env.prod up -d