name: CI/CD

on: [push, pull_request]

jobs:
  test:
    if: ${{ && github.event_name == 'push'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create network
        run: docker network create database
      - name: Build the stack
        run: docker-compose -f "docker-compose-test.yml" --env-file .env.test up -d
      - name: Perform backend tests
        continue-on-error: true
        run: docker exec fastapi python -m pytest
      - name: setup database for frontend testing
        run: | 
          docker exec postgresdb psql -U postgres -c "CREATE DATABASE test;"
          docker exec fastapi aerich init -t app.db.TORTOISE_ORM
          docker exec fastapi aerich init-db
          docker exec -u postgres postgresdb psql test postgres -f /sql_files/setup_testdata.sql
      - name: Build frontend tests image
        run: docker build -t playwright-tests ./frontend-testing/.
      - name: Run frontend tests image
        continue-on-error: true
        run: docker run playwright-tests



  deploy:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd nuxt-fastapi-docker-base
          docker-compose -f docker-compose-prod.yml --env-file .env.prod down
          git pull
          docker-compose -f docker-compose-prod.yml --env-file .env.prod build
          docker-compose -f docker-compose-prod.yml --env-file .env.prod up -d