name: Tests

on:
  push:
    branches:    
      - 'master'   # excludes master

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: Create network
      #   run: docker network create database
      - name: Build and run the docker compose stack
        run: docker-compose -f "docker-compose-test.yml" --env-file .env.test up -d
      - name: Perform unit tests
        run: docker-compose -f docker-compose-test.yml --env-file .env.test exec -T fastapi python -m pytest -v -m unittest  
      - name: Perform api tests
        run: docker-compose -f docker-compose-test.yml --env-file .env.test exec -T fastapi python -m pytest -v -m apitest  

  test-frontend:
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          pip install -e .
      - name: Ensure browsers are installed
        run: python -m playwright install
      - name: Install operating system dependencies
        run: python -m playwright install-deps
      - name: Run your tests
        run: pytest -m frontendtest