name: Tests

on:
  push:
    branches:    
      - 'master'   # excludes master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create network
        run: docker network create database
      - name: Build the stack
        run: docker-compose -f "docker-compose-test.yml" --env-file .env.test up -d
      - name: Perform unit tests
        continue-on-error: true
        run: docker-compose -f docker-compose-dev.yml --env-file .env.dev exec fastapi python -m pytest -v -m unittest
      # - name: setup database for frontend testing
      #   run: | 
      #     docker exec database psql -U postgres -c "CREATE DATABASE test;"
      #     docker exec fastapi aerich init -t app.db.TORTOISE_ORM
      #     docker exec fastapi aerich init-db
      #     docker exec -u postgres database psql test postgres -f /sql_files/setup_testdata.sql
      # - name: Build frontend tests image
      #   run: docker build -t playwright-tests ./frontend-testing/.
      # - name: Run frontend tests image
      #   continue-on-error: true
      #   run: docker run playwright-tests